defaultNetwork: testnet
networks:
  - name: mainnet
    consensusNodes: []
    mirrorNodeUrl: https://mainnet.mirrornode.hedera.com/
  - name: previewnet
    consensusNodes: []
    mirrorNodeUrl: https://previewnet.mirrornode.hedera.com/
  - name: testnet
    consensusNodes: []
    mirrorNodeUrl: https://testnet.mirrornode.hedera.com
accounts:
  - accountId: 0.0.48513659
    privateKey:
      key: '0x8830990f02fae1c3a843b8510d0433a73ee47b08d56426a8e416d08727ea0609'
      type: ED25519
    network: testnet
    alias: AlbertoED25519
    importedTokens: []
  - accountId: 0.0.48587748
    privateKey:
      key: '0x3c8055953320b1001b93f6c99518ec0a1daf7210f1bb02dd11c64f3dec96fdb6'
      type: ECDSA
    network: testnet
    alias: AlbertoECDSA
    importedTokens: []
logs:
  path: ./logs
  level: ERROR
factories:
  - id: 0.0.49077033
    network: testnet
  - id: 0.0.11111111
    network: previewnet
hederaERC20s:
  - id: 0.0.49077027
    network: testnet
  - id: 0.0.11111111
    network: previewnet
